Use git ref for tagging releases (#19)
This patch:
- adds support for tagged releases to improve backwards compatibility and reduce breakage for users of this action
- renames the `build_and_test` workflow to `release`
- adds a warning to the `README` that this action is still very much in flux

Signed-off-by: Krzysztof Bieganski <kbieganski@antmicro.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Build and test
+name: Release
 on: [push, workflow_dispatch, repository_dispatch]
 
 permissions: write-all
@@ -9,17 +9,32 @@ jobs:
     permissions:
       pull-requests: read
     outputs:
-      build: ${{ steps.filter.outputs.build }}
+      build: ${{ steps.build-needed.outputs.build }}
     steps:
       - uses: actions/checkout@v3
 
       - uses: dorny/paths-filter@v2
         id: filter
         with:
-          base: ${{ github.ref }}
+          base: ${{ github.ref_name }}
           filters: |
             build:
               - 'br2-external/**'
+
+      - name: check if release exists
+        id: check-release
+        run: |
+          # gh release view returns non-zero if no such release exists
+          echo "build=$(gh release view ${{ github.ref_name }} &> /dev/null && echo $? || echo $?)" >> $GITHUB_OUTPUT
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: check if build is needed
+        id: build-needed
+        run: |
+          # Step outputs apparently are strings, so we have to compare against literals to avoid silly JS type coercion issues.
+          echo "build=${{ steps.filter.outputs.build == 'true' || steps.check-release.outputs.build != '0' }}" >> $GITHUB_OUTPUT
+
   build:
     runs-on: ubuntu-latest
     needs: changes
@@ -41,7 +56,7 @@ jobs:
           repo_token: "${{ github.token }}"
           file: images.tar.xz
           asset_name: images.tar.xz
-          tag: latest
+          tag: ${{ github.ref_name }}
           overwrite: true
 
   default-configuration-test:
@@ -61,7 +76,6 @@ jobs:
         uses: ./
         with:
           shared-dir: ./tests
-          image: https://github.com/${{ github.repository }}/releases/download/latest/images.tar.xz
           renode-run: |
             wget example.org
             gpiodetect
